version: 'latest'

services:

  notebook:
    container_name: jupyterlab
    hostname: jupyter.local
    build:
      context: ./dockers/jupyterlab
    ports:
      # jupyterlab
      - "8888:8888"
      # mlflow
      #- "5959:5959"
      #flask
      #- "8181:8181"
    volumes:
      - .:/usr/src
      - ./volume/volume:/opt/conda/lib/python3.9/volume
    working_dir: /usr/src
    tty: true # if no command exec, the container still alive
  feature_store:
    container_name: feast
    hostname: feast
    build:
      context: ./dockers/feast
    ports:
      - "9696:9696"
    working_dir: /usr/src #
    tty: true #
  mlflow:
    container_name: mlflow
    hostname: mlflow
    build: 
      context: ./dockers/mlflow
    ports:
      - "5959:5959"
    working_dir: /usr/src #
    tty: true #
  dtale:
    container_name: dtale
    hostname: dtale
    build:
      context: ./dockers/dtale
    ports:
      - "8181:8181"
    working_dir: /usr/src/
    volumes:
      - .:/usr/src/dtale
    tty: true #
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'Migraine-Classification'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234' #This is a really good password 
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - .:/usr/src
      - .:/usr/src/var/lib/mysql
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234